prep-javascript-objects
bugass/javascript-prep-0423-code-solutions pull request #7
Opened 2023-04-19 21:22 UTC by bugass

![Screenshot 2023-04-19 at 2 17 57 PM](https://user-images.githubusercontent.com/102183396/233203098-173e7c2c-1394-49d1-b8af-16d011bc933f.png)

2023-04-19 23:36 UTC, Zhiwutian requested changes
a couple small updates, watch for those details in the instructions!

2023-04-19 23:36 UTC, Zhiwutian commented on prep-javascript-objects/main.js
> +  previousJob: 'Techstack Admin',
the job property should be added to the object using dot notation. 
the previous job property should be added to the object using bracket notation.

2023-04-19 23:58 UTC, bugass commented
![Screenshot 2023-04-19 at 4 51 52 PM](https://user-images.githubusercontent.com/102183396/233223948-ecefac8f-af9b-4ef0-92de-6a451f114d98.png)

Hi Brett,

ahh yes, i think i was confused and was trying to come up with another way to get the same result.

I think i have updated the code to be correct, utilizing nesting within the variable for my objects, and updating the current job to use dot notation to request from the variable/object tree.

Thank you

2023-04-20 17:21 UTC, Zhiwutian approved these changes
That was an interesting way to go!

2023-04-21 16:05 UTC, merged